### PR TITLE
Add package.json for NPM publish

### PR DESCRIPTION
**Pull request by Craga89**
As noted in Issue #57, it'd be great if we could get this published as an NPM package for those of us using Browserify/Webpack workflows!

Just needs this merged to add the missing `package.json` file, and an `npm publish` from yourself whilst in the `gh-pages` branch.

### CODE REVIEW

**Comment by mbest** [comment]
Great! This makes it easy.

**Comment by crissdev** [comment]
Already taken. Maybe use a dash instead? Or contact the owner of that package. https://www.npmjs.com/package/knockout.punches

**Comment by mbest** [comment]
I think using the dash is better on npm.

**Comment by Craga89** [comment]
:+1: Replaced with a dash instead

**Comment by mbest** [comment]
Thanks. I've published it now.

**Comment by Craga89** [comment]
:+1: @youngjay Any chance we can unpublish your custom `knockout.punches` NPM package? Keeps things clear!

**Comment by crissdev** [comment]
:+1:

**Comment by youngjay** [comment]
Maybe I can transfer the knockout.punches project on NPM to mbest?

**Comment by mbest** [comment]
@youngjay That would be great.

**Comment by youngjay** [comment]
@mbest 
I have add you as owner.
Sorry for disturbing.

**Pull request merged**
